
<h4>Error Handling</h4>
<p>catchError() - is used to gracefully handle errors in an observable stream and return a new observable instead of letting the error terminate the stream.</p>
<p>retry() - it allows to automatically resubscribe to a source observable when it fails with an error for a specified no. of times.</p>
<p>retryWhen() - it gives you full control over how and when to retry the failed observable</p>
<p>throwError() - is used to create an observable that immediately errorsout when subscribed to.</p>